Update integration.gitlab-ci.yml

diff --git a/integration.gitlab-ci.yml b/integration.gitlab-ci.yml
--- a/integration.gitlab-ci.yml
+++ b/integration.gitlab-ci.yml
@@ -1,17 +1,20 @@
 variables:
   SONARQUBE_URL: 'https://sonarqube.u-cloudsolutions.xyz'
   SONARQUBE_TOKEN: 'squ_b730e6c811798750f5442b5ec90950a58600c316'
-  SONARQUBE_PROJECT_KEY: 'nest-js-project'
-  SONARQUBE_PROJECT_NAME: 'nest-js-project'
+  SONARQUBE_PROJECT_KEY: 'my-next-project'
+  SONARQUBE_PROJECT_NAME: 'my-next-project'
+
   NEXUS_CREDENTIALS_ID: "nexus-jenkins"
   NEXUS_URL: "https://nexus.u-cloudsolutions.xyz"
   NEXUS_REPOSITORY: "student-repository"
   GROUP_ID: "com.artificial.Nest-JS"
   ARTIFACT_ID: "artifact"
   ZIP_FILE_NAME: '${ARTIFACT_ID}-${COMMIT_ID}.zip'
-  SLACK_WEBHOOK_URL: 'https://hooks.slack.com/services/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'
+  COMMIT_ID: $(git rev-parse --short HEAD)
+  SLACK_WEBHOOK_URL: 'https://hooks.slack.com/services/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'
 
-image: node:18-alpine
+
+
 stages:
   - checkout
   - install
@@ -32,7 +35,7 @@ stages:
 checkout:
   stage: checkout
   tags:
-    - nest-run
+    - shell
   script:
     - echo "Checking out the repository"
     - git rev-parse --short HEAD > commit_hash.txt
@@ -52,16 +55,17 @@ checkout:
 install_dependencies:
   stage: install
   script:
-    - rm -rf node_modules 
+    - rm -rf  node_modules
     - npm install  # Clean install dependencies based on package-lock.json
   tags:
-    - nest-run
+    - docker-node
   after_script:
+    -  apk add --no-cache curl
     - |
       if [ $? -eq 0 ]; then
-        SLACK_MESSAGE="Install dependencies succeeded in pipeline $CI_PIPELINE_ID"
+        SLACK_MESSAGE="install_dependencies succeeded in pipeline $CI_PIPELINE_ID"
       else
-        SLACK_MESSAGE="Install dependencies failed in pipeline $CI_PIPELINE_ID"
+        SLACK_MESSAGE="install_dependencies failed in pipeline $CI_PIPELINE_ID"
       fi
       curl -X POST -H 'Content-type: application/json' \
         --data "{\"text\":\"$SLACK_MESSAGE\"}" \
@@ -70,119 +74,151 @@ install_dependencies:
 build:
   stage: build
   script:
-    - npm run build  # Run the build script defined in your package.json
-  artifacts:
-    paths:
-      - .next/  # Adjust this if your build output goes elsewhere
+    - npm install
+    - npm run build  # Explicitly run the Nest CLI
   tags:
-    - nest-run
+    - docker-node
   after_script:
+    -  apk add --no-cache curl
     - |
       if [ $? -eq 0 ]; then
-        SLACK_MESSAGE="Build succeeded in pipeline $CI_PIPELINE_ID"
+        SLACK_MESSAGE="build succeeded in pipeline $CI_PIPELINE_ID"
       else
-        SLACK_MESSAGE="Build failed in pipeline $CI_PIPELINE_ID"
+        SLACK_MESSAGE="build failed in pipeline $CI_PIPELINE_ID"
       fi
       curl -X POST -H 'Content-type: application/json' \
         --data "{\"text\":\"$SLACK_MESSAGE\"}" \
         $SLACK_WEBHOOK_URL
+
+
 
 unit_tests:
   stage: test
   script:
+    - npm install
+    - npm run build
+
     - npm run test  # Run the test script defined in your package.json
-    - npm run test:e2e  # Optionally run end-to-end tests if defined
-  artifacts:
-    when: always
-    paths:
-      - test-results/  # Adjust this path if you have test result outputs
   tags:
-    - nest-run
+    - docker-node
   after_script:
+    -  apk add --no-cache curl
     - |
       if [ $? -eq 0 ]; then
-        SLACK_MESSAGE="Unit tests succeeded in pipeline $CI_PIPELINE_ID"
+        SLACK_MESSAGE="unit_tests succeeded in pipeline $CI_PIPELINE_ID"
       else
-        SLACK_MESSAGE="Unit tests failed in pipeline $CI_PIPELINE_ID"
+        SLACK_MESSAGE="unit_tests failed in pipeline $CI_PIPELINE_ID"
       fi
       curl -X POST -H 'Content-type: application/json' \
         --data "{\"text\":\"$SLACK_MESSAGE\"}" \
         $SLACK_WEBHOOK_URL
 
-code_quality:
+quality:
   stage: quality
-  script:
-    - sonar-scanner \
-        -Dsonar.projectKey=$SONARQUBE_PROJECT_KEY \
-        -Dsonar.projectName=$SONARQUBE_PROJECT_NAME \
-        -Dsonar.host.url=$SONARQUBE_URL \
-        -Dsonar.login=$SONARQUBE_TOKEN
   tags:
-    - nest-run
+    - sonar
+  script:
+    - echo "Running code quality check via SonarQube"
+    - sonar-scanner -X -Dsonar.projectKey=${SONARQUBE_PROJECT_KEY} -Dsonar.sources=. -Dsonar.host.url=${SONARQUBE_URL} -Dsonar.login=${SONARQUBE_TOKEN} -Dsonar.exclusions=vendor/**
   after_script:
     - |
       if [ $? -eq 0 ]; then
-        SLACK_MESSAGE="Code quality analysis succeeded in pipeline $CI_PIPELINE_ID"
+        SLACK_MESSAGE="quality succeeded in pipeline $CI_PIPELINE_ID"
       else
-        SLACK_MESSAGE="Code quality analysis failed in pipeline $CI_PIPELINE_ID"
+        SLACK_MESSAGE="quality failed in pipeline $CI_PIPELINE_ID"
       fi
       curl -X POST -H 'Content-type: application/json' \
         --data "{\"text\":\"$SLACK_MESSAGE\"}" \
         $SLACK_WEBHOOK_URL
+  
+
 
 quality_gate:
   stage: quality_gate
-  script:
-    - sonar-quality-gate-check \
-        -Dsonar.projectKey=$SONARQUBE_PROJECT_KEY \
-        -Dsonar.host.url=$SONARQUBE_URL \
-        -Dsonar.login=$SONARQUBE_TOKEN
   tags:
-    - nest-run
+    - sonar
+  image: alpine:latest
+  before_script:
+    - apk add --no-cache curl
+  script:
+    - echo "Waiting for SonarQube quality gate..."
+    - sleep 60
+    - echo "Checking SonarQube quality gate status"
+    - |
+      RESPONSE=$(curl -s -u ${SONARQUBE_TOKEN}: \
+        "${SONARQUBE_URL}/api/qualitygates/project_status?projectKey=${SONARQUBE_PROJECT_KEY}")
+      if echo "$RESPONSE" | grep -q '"status":"OK"'; then
+        echo "Quality gate passed"
+      else
+        echo "Quality gate failed"
+        exit 1
+      fi
   after_script:
     - |
       if [ $? -eq 0 ]; then
-        SLACK_MESSAGE="Quality gate check passed in pipeline $CI_PIPELINE_ID"
+        SLACK_MESSAGE="quality_gate succeeded in pipeline $CI_PIPELINE_ID"
       else
-        SLACK_MESSAGE="Quality gate check failed in pipeline $CI_PIPELINE_ID"
+        SLACK_MESSAGE="quality_gate failed in pipeline $CI_PIPELINE_ID"
       fi
       curl -X POST -H 'Content-type: application/json' \
         --data "{\"text\":\"$SLACK_MESSAGE\"}" \
         $SLACK_WEBHOOK_URL
 
-package_artifact:
+
+
+
+
+package:
   stage: package
+  tags:
+    - shell
   script:
-    - zip -r $ZIP_FILE_NAME dist/
+    - echo "Cleaning up old ZIP files..."
+    - rm -f artifact-*.zip
+    - echo "Packaging project..."
+    - COMMIT_ID=$(git rev-parse --short HEAD)
+    - ZIP_FILE_NAME="artifact-${COMMIT_ID}.zip"
+    - echo "Packaging project as ${ZIP_FILE_NAME}..."
+    - zip -r ${ZIP_FILE_NAME} .
+    - ls -l ${ZIP_FILE_NAME}
+  after_script:
+    - |
+      if [ $? -eq 0 ]; then
+        SLACK_MESSAGE="package succeeded in pipeline $CI_PIPELINE_ID"
+      else
+        SLACK_MESSAGE="package failed in pipeline $CI_PIPELINE_ID"
+      fi
+      curl -X POST -H 'Content-type: application/json' \
+        --data "{\"text\":\"$SLACK_MESSAGE\"}" \
+        $SLACK_WEBHOOK_URL
+
   artifacts:
     paths:
-      - $ZIP_FILE_NAME
+      - artifact-*.zip
+
+
+upload:
+  stage: upload
   tags:
-    - nest-run
+    - shell
+  script:
+    - echo "Determining commit ID..."
+    - COMMIT_ID=$(git rev-parse --short HEAD)
+    - ZIP_FILE_NAME="artifact-${COMMIT_ID}.zip"
+    - echo "Uploading ${ZIP_FILE_NAME} to Nexus..."
+    - UPLOAD_URL="${NEXUS_URL}/repository/${NEXUS_REPOSITORY}/${GROUP_ID//./\/}/${ARTIFACT_ID}/${COMMIT_ID}/${ZIP_FILE_NAME}"
+    - pwd  # Print working directory
+    - find . -name "*.zip"  # Find ZIP files
+    - ls -l ${ZIP_FILE_NAME}  # Verify file existence
+    - curl -u wissem:3FqNnJ6XzF --upload-file "${ZIP_FILE_NAME}" "${UPLOAD_URL}"
   after_script:
     - |
       if [ $? -eq 0 ]; then
-        SLACK_MESSAGE="Packaging succeeded in pipeline $CI_PIPELINE_ID"
+        SLACK_MESSAGE="upload succeeded in pipeline $CI_PIPELINE_ID"
       else
-        SLACK_MESSAGE="Packaging failed in pipeline $CI_PIPELINE_ID"
+        SLACK_MESSAGE="upload failed in pipeline $CI_PIPELINE_ID"
       fi
       curl -X POST -H 'Content-type: application/json' \
         --data "{\"text\":\"$SLACK_MESSAGE\"}" \
         $SLACK_WEBHOOK_URL
 
-upload_artifact_to_nexus:
-  stage: upload
-  script:
-    - curl -u $NEXUS_CREDENTIALS_ID -T $ZIP_FILE_NAME "$NEXUS_URL/repository/$NEXUS_REPOSITORY/$GROUP_ID/$ARTIFACT_ID/$COMMIT_ID/$ZIP_FILE_NAME"
-  tags:
-    - nest-run
-  after_script:
-    - |
-      if [ $? -eq 0 ]; then
-        SLACK_MESSAGE="Upload to Nexus succeeded in pipeline $CI_PIPELINE_ID"
-      else
-        SLACK_MESSAGE="Upload to Nexus failed in pipeline $CI_PIPELINE_ID"
-      fi
-      curl -X POST -H 'Content-type: application/json' \
-        --data "{\"text\":\"$SLACK_MESSAGE\"}" \
-        $SLACK_WEBHOOK_URL
